### PR TITLE
Ft bug fixes

### PR DESCRIPTION
**Pull request by ringtho**
Please review my PR for adding a map to the UI page of creating an incident @kalsmic, @BrunoNicholas, @brucenelm, @Phionanamugga

### CODE REVIEW

**Comment by BrunoNicholas** [comment]
I see there is an error with the naming of the HTML pages.
I could suggest using underscores to recognise it as one string of name. i.e. ```corruption_login.html``` instead of the current

**Comment by kalsmic** [comment]
- Correct the link to red flags in the menu, it redirects to the corruption.html page.
- Your navigation menu is not consistent please make sure that the links match the names.-\
- Check the link to the CSS files on the admin page
- It will be nice if you placed you UI templates in the UI folder as stated in the Challenge rubric
- The links to the edit button on the incidents list do not work. Consider

**Comment by ghost** [comment]
-I think the user should not access other pages without first logging in, try working on it
-Try to make the record fields functional

**Comment by ringtho** [comment]
iam going to work on the links today. i was first making the changes to the outlook today and deleting the unecessary pages. am going to work on all that feedback today. Thanks for the feedback

**Comment by ringtho** [comment]
I have worked on the feedback that you wonderful people had asked me to work on. Am now going to improve on the responsiveness of UI

**Comment by ringtho** [comment]
> -I think the user should not access other pages without first logging in, try working on it
> -Try to make the record fields functional

I have implemented that for now

**Comment by ringtho** [comment]
> * Correct the link to red flags in the menu, it redirects to the corruption.html page.
> * Your navigation menu is not consistent please make sure that the links match the names.-\
> * Check the link to the CSS files on the admin page
> * It will be nice if you placed you UI templates in the UI folder as stated in the Challenge rubric
> * The links to the edit button on the incidents list do not work. Consider

I have placed the templates in the UI folder and added a link to the edit button. Thanks Arthur

**Comment by ringtho** [comment]
> I see there is an error with the naming of the HTML pages.
> I could suggest using underscores to recognise it as one string of name. i.e. `corruption_login.html` instead of the current

Ohh yeah i have corrected all the files and named them perfectly. Kudos to the feedback

**Review by kalsmic — COMMENTED** [review]
Ids must be unique. These ids are related to functionality, write a reusable function and pass on to it the unique is for the specific item.

**Review by kalsmic — COMMENTED** [review]
Check in your "admin.html" for more clarification on the unique id issue.

**Pull request merged**
